[project]
name = "supply-chain-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Krishna Kiriti", email = "165306327+Krishnakb6@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.12.3",
    "dbt-databricks>=1.12.5",
]

[project.scripts]
supply-chain-project = "supply_chain_project:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
